version: '3'

services:
  app:
    image: node:13
    container_name: shoppingmate--api
    restart: unless-stopped
    ports:
      - "8080:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    working_dir: /app
    networks:
      - app-network
    environment:
      - DB_PATH=${DB_PATH:-default}
      - CORS_PATH=${CORS_PATH:-default}
      - MANAGE_CATEGORIES=${MANAGE_CATEGORIES:-default}
    command: bash -c "npm install -g pm2 && npm install && pm2-runtime server.js"

networks:
  app-network:
    driver: bridge

volumes:
  node_modules:
