name: build and deploy build

on:
  push:
    branches: [ deploy-custard ]
  pull_request:
    branches: [ deploy-custard ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts
      - uses: actions/checkout@v1
      - name: npm install and build webpack
        env:
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_port: 22
          remote_user: 'build'
          client_local_dir: "build"
          client_remote_dir: "~/shoppingmate_client/"
          REACT_APP_APIPATH: ${{ secrets.DEPLOY_APIPATH }}
          server_local_dir: "server"
          server_remote_dir: "~/shoppingmate_server/"
        run: |
          rsync -avzr --delete -e "ssh -p ${remote_port} -o StrictHostKeyChecking=no" ${server_local_dir} ${remote_user}@${remote_host}:${server_remote_dir}
          ssh ${remote_user}@${remote_host} "cp ~/shoppingmate_server/.env ~/shoppingmate_server/server/"
          ssh ${remote_user}@${remote_host} "docker restart shoppingmate--api"
          cd client
          npm install
          npm run build
          rsync -avzr --delete -e "ssh -p ${remote_port} -o StrictHostKeyChecking=no" ${client_local_dir} ${remote_user}@${remote_host}:${client_remote_dir}
          
